### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by wanghaojie1024** [happypepper/DeepHoldem#2]
![image](https://user-images.githubusercontent.com/12696298/41137535-21542c14-6b0e-11e8-8035-11b4d2c13458.png)
I tried to run the agent, but encountered a problem as the screen shot shows.

By the way, which IDE did you use to debug? I can't find a convenient lua IDE.
I can't run DataGeneration also, even i reduce the params.train_data_count and params.gen_batch_size to 10, 10 respectively. It's also memory error. 

I used 32 cpu server with 64GB Memory to run thest code.

And the problem seems to be caused by lookahead, if I do nothing but require lookahead, I will get this error.

Thanks!

**Comment by happypepper** [comment]
I've seen this error before if I installed torch with luaJIT. Can you confirm that you installed torch with lua5.2 instead?

**Comment by wanghaojie1024** [comment]
Installing lua5.2 solved this problem。
