### ISSUE TITLE
preflop sizings

### ISSUE THREAD

**Issue by juggler123** [happypepper/DeepHoldem#20]
Where in this can it be altered to include preflop sizes other than call/pot/allin?

**Comment by aikupoker** [comment]
Hi @juggler123 

I don't understand your question but I'll try to help you.

Inside happypepper there is a preflop network already trained. This network can made:
- Raise (amount). This amount varies depending on the situation.
- Check (if there is no opponent bet)/Call (bet the same as the opponent does).
- Fold.

If you want to modify the pot size during data training (for No Limit), just go here and modify it:

https://github.com/happypepper/DeepHoldem/blob/master/Source/DataGeneration/data_generation.lua#L73-L74

Good luck!

**Comment by aikupoker** [comment]
DeepStack uses following actions to generate poker situations:
 * Fold.
 * Call/Check.
 * Bet Half Pot (0.5p).
 * Bet Pot (1p).
 * All-in.

DeepHoldem uses following actions:
 * Fold.
 * Call/Check.
 * Bet Pot (1p).
 * All-in.

You can add more actions in parameter configuration file:

```
params.bet_sizing = {{1},{1},{1}}
```

You can't remove following actions:
 * Fold.
 * Call/Check.
 * All-in.
