### ISSUE TITLE
Pot Sizes

### ISSUE THREAD

**Issue by herrefirh** [happypepper/DeepHoldem#21]
What's the calculation behind the min_pot | max_pot NL settings?
```lua
min_pot = {100,200,400,2000,6000}
max_pot = {100,400,2000,6000,18000}
```
I'm changing stack size and number of players. (4000 stack, 3 players)

With two players, no bet, just blinds and antes already there is 250 on the preflop so why min/max 100?. I guess if you can bet 100 on the flop,turn river that might explain 100 min, (why not 0 in that case). Maybe the idea being you call the 100 so that's the 'max' as well?

```lua
--- the size of the game's ante, in chips
params.ante = 100
params.sb = 50
params.bb = 100
--- the size of each player's stack, in chips
params.stack = 20000
```
And on the river, max (if we use acpc concept of maxspent) would be 40,000 (or 39,500 otherwise). Even if we are bucketing everything above 18,000 to be in 18,000 bucket, I wonder how you came about those particular numbers?

I just wonder because I will have 3 players (thus larger pots), but with smaller stacks, if you computed relative to blinds, stack sizes, or out of hat.

**Comment by aikupoker** [comment]
Hi @herrefirh 

If you go here: https://www.deepstack.ai/downloads

And download the "Supplement (.pdf)" and move to page 11 and 12 (bottom). They match with that values (or closely):

> intervals {[100, 100), [200, 400), [400, 2000), [2000, 6000), [6000, 19950]}

Image that you want to create a training data. These values will give you a uniform set of what kind of data you will have (different pot size for each training data). These intervals are extracted from a old HUNL program (not documented).

I hope this answer helps you.

**Comment by herrefirh** [comment]
Very cool @aikupoker, thanks!
