### ISSUE TITLE
Problem with data generation

### ISSUE THREAD

**Issue by matthiasanderer** [happypepper/DeepHoldem#3]
I am a bit stuck how to do the data generation:

When starting: th DataGeneration/main_data_generation.lua 4

I get the follwing error:

./Nn/value_nn.lua:71: attempt to index field 'mlp' (a nil value)

Did anyone solve this problem before?

What is the process for data generation/ model training (with GPU) that works for you?

Thank you!

**Comment by happypepper** [comment]
It is a bit odd that you run into this since `ValueNn:get_value()` shouldn't be called for river generation.  Did you modify the code? or maybe you are trying to generate for flop or turn?

**Comment by matthiasanderer** [comment]
The only modifications I did is set GPU flag to true.

I get the error for street params 4, 3 and 2.... All the same

Can you give a hint how to generate All models starting from the latest
commit?

Thank you a lot.

Lawson He <notifications@github.com> schrieb am Mi., 13. Juni 2018, 03:13:

**Comment by happypepper** [comment]
Flop and turn should not work until you generate river first. The error you posted is expected for flop and turn. Are you sure you are getting the same error for river?

**Comment by matthiasanderer** [comment]
Ok - I think the other errors I get are from other issues than training order -> will open a new issue

**Comment by lorrp1** [comment]
i have trained the sample and created the river model, now i get the same error. i had changed the folders, and maybe its because it does not recognize the input from "river", so i have tried to recreate the default folders but i still get the same error:

/home/painkillerrr/torch/install/bin/lua: ./Nn/value_nn.lua:71: attempt to index a nil value (field 'mlp')
stack traceback:
	./Nn/value_nn.lua:71: in method 'get_value'
	./Nn/next_round_value.lua:215: in method 'get_value'
	./Lookahead/lookahead.lua:259: in method '_compute_terminal_equities_next_street_box'
	./Lookahead/lookahead.lua:323: in method '_compute_terminal_equities'
	./Lookahead/lookahead.lua:93: in method '_compute'
	./Lookahead/lookahead.lua:47: in method 'resolve_first_node'
	./Lookahead/resolving.lua:59: in method 'resolve_first_node'
	./DataGeneration/data_generation.lua:132: in function 'DataGeneration.data_generation.generate_data_file'
	./DataGeneration/data_generation.lua:24: in function 'DataGeneration.data_generation.generate_data'
	DataGeneration/main_data_generation.lua:14: in main chunk
	[C]: in function 'dofile'
	...errr/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?
