### ISSUE TITLE
Be the Dealer

### ISSUE THREAD

**Issue by Masegi** [happypepper/DeepHoldem#32]
Is there an option to actually "be the dealer"? So like given the DeepHoldem the state of the board and it will respond with it's next step? 

I read a thread where you descripted how you let DeepHoldem play against Slumbot (you were talking about a js source), where can I find it?

I would love to use it as a board/hand eval tool, but my c experience is really bad and i'm trien to use it from a c# app.

Sorry that I open an issue, but I have no idea how to reach you.

**Comment by aikupoker** [comment]
Hi @Masegi 

You can read how to play against Slumbot in my fork of this repository: https://github.com/aikupoker/deeper-stacker#playing-vs-slum-bot

It is not a JavaScript source, it is a Python script using Selenium.

**Comment by Masegi** [comment]
ok thanks, i didnt saw that first, sry
