### ISSUE TITLE
handle zero reach strategy

### ISSUE THREAD

**Issue by wanghaojie1024** [happypepper/DeepHoldem#6]
![image](https://user-images.githubusercontent.com/12696298/41390773-b4541960-6fc9-11e8-9186-e8c2008c7d4a.png)

Hello !
can you explain these two lines, it seems it has no effect at all to me.
Maybe it's a fancy implementation which used special feature of torch?

@happypepper

**Comment by happypepper** [comment]
Yes, I believe it's a torch thing. This is in deepstack-leduc as well
```
th> 0/0 == 0/0
false
```
In torch NaN != NaN, so this code is used to detect NaN which will happen if the reach probability is 0. In those cases, it will set fold probability to 1 and other actions to 0.

**Comment by wanghaojie1024** [comment]
@happypepper thanks!
