### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lh14576** [happypepper/DeepHoldem#8]
Hi,

when trying to do a preflop match with deepstack I am getting a "Segmentation fault (core dumped)" error. It doesn't matter if I skip the bucket computation or not. Running on Ubuntu 18.04

Any hints on how to resolve this?

**Comment by happypepper** [comment]
This could be related to your lua version, since luaJIT will produce out of memory errors.

Are you using luaJIT or lua 5.2?

**Comment by lh14576** [comment]
pretty sure its lua 5.2. It says "Lua 5.2" when doing print(_VERSION). Also, it is counting all possible flop combinations up to 22100 before crashing with the segmentation fault.

**Comment by happypepper** [comment]
`th` may be using different version of lua than `lua`.
Are there more detailed error logs?
did you install torch using `TORCH_LUA_VERSION=LUA52 ./install.sh`?

**Comment by lh14576** [comment]
yeah, I installed as described in the readme. Also, I started `th` before using `print(_VERSION)` that should give me the lua used by torch right?

**Comment by happypepper** [comment]
Yea it should.
I think the problem is your machine doesn't have enough RAM. It runs fine on my macbook with 16 GB RAM.
I should add some system requirements to the readme.

**Comment by lorrp1** [comment]
i have setup everything but its very slow on my 1070 so im thinking of running it on google cloud; but how did you tested it versus "Slumbot 2017"?

**Comment by lh14576** [comment]
I increased RAM to 32GB but that didn't help. Still crashing with segmentation fault after counting flops.

**Comment by lorrp1** [comment]
try to install torch with lua 5.3 i could not run it on 5.2

**Comment by lh14576** [comment]
same with lua 5.3. Will try on ubuntu 16.04 and see if that helps.

**Comment by lh14576** [comment]
Thanks guys. Fresh install on Ubuntu 16.04 solved the issue.

**Comment by ghost** [comment]
@lh14576   the root cause is that 52 should be LUA52 in readme "TORCH_LUA_VERSION=52 ./install.sh". I encounter the same issue. I fixed it when I use LUA52. 

hope helpful for you.

**Comment by godmoves** [comment]
I think this is an issue related to Ubuntu. I've tested on Ubuntu 18.04 many times and failed every time. But the same code running smoothly on Ubuntu 16.04. BTW, LuaJIT will not get segfault but will produce memory error.

**Comment by krunt** [comment]
Encountered this too on 18.04. 
Solved this by running in nvidia-docker 16.04, torch built from source
using https://github.com/nagadomi/cutorch.
actually copying this built torch to 18.04 and running - sigfault does not happen:)
